services:
  app:
    build: .
    container_name: python_app
    volumes:
      - .:/Clima
    env_file:
      - .env # Define el archivo .env que contiene las variables de entorno
    stdin_open: true  # Para permitir modo interactivo
    tty: true         # Asigna una pseudo-terminal
    command: python app.py